#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-slave'
    }
    stages {
        stage('Compile') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn clean compile"
		    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn test"
		    }
                }
            }
        }
        stage('package') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn package"
		    }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn install"
		    }
                }
            }
        }
    }
}
