#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-slave'
    }
    stages {
        stage('Compile') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn clean compile"
		    }
                }
            }
        }
        stage('Parallel Stages') {
	   parallel {	
		stage('Unit Test') {
		    steps {
			script {
			    dir("Day2/multi-module-project") {
				sh "mvn test"
			    }
			}
		    }
		}

		stage('Static Code Analyis - SonarQube') {
		    steps {
			script {
			    dir("Day2/multi-module-project") {
				sh "mvn clean verify sonar:sonar \
					  -Dsonar.projectKey=multimodule \
					  -Dsonar.host.url=http://192.168.167.161:9000 \
					  -Dsonar.login=sqp_5ef8542b307f543c129b9ef3b902e9bf48257a14"
			    }
			}
		    }
		}
	   }
	}
        stage('package') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn package"
		    }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn install"
		    }
                }
            }
        }
    }
}
